name: PurchaseCheck
version: '${project.version}'
main: net.apepvp.purchasecheck.PurchaseCheck
api-version: '1.20'
author: SuXuan_Dev
depend:
  - ApeCore
description: Purchase check plugin of server "apepvp.net"
commands:
  check:
    permission: purchasecheck.command.check
    usage: /check
